version: '3.8'

services:
  postgres_queryshield:
    image: postgres:15
    container_name: Queryshield
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 12345678!
      POSTGRES_DB: queryshield
    ports:
      - "5432:5432"  # Map to a different host port if needed
    volumes:
      - pg_data_queryshield:/var/lib/postgresql/data

  postgres_verification:
    image: postgres:15
    container_name: QueryshieldVerification
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: 12345678!
      POSTGRES_DB: queryshield_verification
    ports:
      - "5433:5432"  # Expose on a different host port
    volumes:
      - pg_data_verification:/var/lib/postgresql/data

volumes:
  pg_data_queryshield:
  pg_data_verification:
